---
collections:
  - name: ansible.controller
    version: 4.5.0
  - name: ansible.posix
    version: 1.3.0
  - name: ansible.security
    version: 1.0.0
  - name: ansible.utils
    version: 3.0.0
  - name: ansible.yang
    version: 1.0.0
  - name: ansible.windows
    version: 2.2.0
  - name: ansible.netcommon
    version: 6.0.0
  - name: ansible.network
    version: 1.2.0
  # redhat
  - name: redhat_cop.controller_configuration
    version: 2.3.1
  - name: redhat.insights
    version: 1.2.2
  - name: redhat.rhel_system_roles
    version: 1.22.0
  - name: redhat.satellite
    version: 4.0.0
  - name: redhat.satellite_operations
    version: 2.1.0
  # community
  - name: community.general
    version: 8.3.0
  - name: community.windows
    version: 2.1.0
  # containers
  - name: containers.podman
    version: 1.11.0
  # windows
  - name: chocolatey.chocolatey
    version: 1.5.1
  # cloud
  - name: azure.azcollection
    version: 2.1.1
  - name: amazon.aws
    version: 7.2.0
  - name: cloud.common
    version: 2.1.1
  # cisco
  - name: cisco.ios
    version: 6.1.0
  - name: cisco.nxos
    version: 6.0.0
  - name: cisco.iosxr
    version: 7.1.0
  - name: cisco.asa
    version: 3.0.0
  # extra
  - name: arista.eos
    version: 5.0.0
  - name: frr.frr
    version: 2.0.0
  - name: ibm.qradar
    version: 2.0.0
  - name: junipernetworks.junos
    version: 3.0.0
  - name: kubernetes.core
    version: 2.2.3
  - name: openvswitch.openvswitch
    version: 2.1.0
  - name: servicenow.itsm
    version: 1.3.3
  - name: splunk.es
    version: 2.0.0
  - name: trendmicro.deepsec
    version: 2.0.0
  - name: vmware.vmware_rest
    version: 2.1.5
  - name: vyos.vyos
    version: 3.0.0
