---
collections:
  - name: ansible.controller
    version: 4.5.0
  - name: redhat_cop.controller_configuration
    version: 2.3.1
  # linux
  - name: redhat.insights
    version: 1.2.2
  - name: redhat.rhel_system_roles
    version: 1.22.0
  - name: community.general
    version: 8.3.0
  - name: containers.podman
    version: 1.11.0
  # windows
  - name: chocolatey.chocolatey
    version: 1.5.1
  - name: community.windows
    version: 2.1.0
  - name: ansible.windows
    version: 2.2.0
  # cloud
  - name: azure.azcollection
    version: 2.1.1
  - name: amazon.aws
    version: 7.2.0
  # satellite
  - name: redhat.satellite
    version: 4.0.0
  - name: redhat.satellite_operations
    version: 2.1.0
  # network
  - name: cisco.ios
    version: 6.1.0
  - name: cisco.nxos
    version: 6.0.0
  - name: cisco.iosxr
    version: 7.1.0
  - name: ansible.netcommon
    version: 6.0.0
