---
plugin: azure.azcollection.azure_rm

include_vm_resource_groups:
  - "*"

conditional_groups:
  all_the_hosts: true
  rhel: "'RHEL' in image.offer"
  windows: "'WindowsServer' in image.offer"

keyed_groups:
  - prefix: tag
    key: tags
  - prefix: azure_loc
    key: location

exclude_host_filters:
  - powerstate != 'running'
