---
- name: Update RHEL VMs with desired packages
  hosts: "{{ HOSTS | default('rhel') }}"
  tasks:
    - name: Update installed packages
      ansible.builtin.dnf:
        name: "*"
        state: latest
