---
- name: Update RHEL VMs with desired packages
  hosts: "{{ HOSTS | default('rhel') }}"
  vars:
    detailedreport: True
    file_path: /var/www/html/reports
  tasks:
      - name: Install the latest version of Apache
        ansible.builtin.dnf:
          name:
            - httpd
          state: latest

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: "{{ file_path }}"
        state: directory
        mode: '0755'

    - name: create HTML report
      ansible.builtin.template:
        src: ./templates/report.j2
        dest: "{{ file_path }}/linux.html"
      check_mode: no

    - name: copy CSS over
      ansible.builtin.copy:
        src: "./files/css"
        dest: "{{ file_path }}"
        directory_mode: true
      check_mode: no

    - name: copy logos over
      ansible.builtin.copy:
        src: "{{ item }}" 
        dest: "{{ file_path }}"
        directory_mode: true
      loop:
        - "./files/webpage_logo.png"
        - "./files/redhat-ansible-logo.svg"
        - "./files/server.png"
      check_mode: no

    - name: Make sure httpd service unit is running
      ansible.builtin.systemd:
        state: started
        name: httpd.service
        enabled: yes

    - name: Permit traffic in default zone for http service
      ansible.posix.firewalld:
        service: http
        permanent: yes
        state: enabled

    - name: Set httpd_can_network_connect flag on and persist across reboots
      ansible.posix.seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

    - name: Wait for server to restart
      reboot:
        reboot_timeout: 3600

    - name: display link to inventory report
      ansible.builtin.debug:
        msg: "Please go to http://{{ hostvars[report_server]['ansible_host'] }}/reports/linux.html"