---
- name: Update RHEL VMs with desired packages
  hosts: "{{ HOSTS | default('rhel') }}"
  tasks:
  tasks:
    - name: Install Java 1.7 and some basic dependencies
      yum: 
        name: "{{ item }}"
        state: present
      with_items:
      - unzip
      - java-17-openjdk
      - libselinux-python
      - libsemanage-python

