---
- name: Chocolatey install multiple packages
  hosts: "{{ HOSTS | default('windows') }}"
  vars:
    choco_packages:
      - name: nodejs
      - name: python
  tasks:
  - name: Install specific packages
    win_chocolatey:
      name: "{{ item.name }}"
      state: latest
    loop: "{{ choco_packages }}"

  - name: Check python package version
    win_command: python --version
    register: check_python_version
    changed_when: false

  - name: Check nodejs package version
    win_command: node --version
    register: check_node_version
    changed_when: false

  - debug:
      msg: Python Version is {{ check_python_version.stdout_lines[0] }} and NodeJS version is {{ check_node_version.stdout_lines[0] }}
