---
- name: Create Azure VM
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create Windows VM
      ansible.builtin.include_role:
        name: ../roles/create_windows_vm