---
- name: Run linux report
  hosts: "{{ HOSTS | default('rhel') }}"
  gather_facts: false
  become: true
  vars:
    harden_firewall: false
    harden_time: false
    harden_ssh: false
    harden_pci: false
    harden_stig: false
    harden_cui: false
    harden_hipaa: false
  tasks:
    - name: Configure Firewall
      when: harden_firewall | bool
      ansible.builtin.include_role:
        name: linux-system-roles.firewall

    - name: Configure Timesync
      when: harden_time | bool
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.timesync

    - name: SSH Hardening
      when: harden_ssh | bool
      ansible.builtin.include_role:
        name: dev-sec.ssh-hardening

    # run with --skip-tags accounts_passwords_pam_faillock_deny
    - name: Apply PCI Baseline
      when: harden_pci | bool
      ansible.builtin.include_role:
        name: redhatofficial.rhel8_pci_dss

    - name: Apply DISA STIG for Red Hat Enterprise Linux 8
      when: harden_stig | bool
      ansible.builtin.include_role:
        name: redhatofficial.rhel8_stig

    - name: Install aide tool
      when: harden_cui | bool
      ansible.builtin.dnf:
        name: aide
        state: latest

    - name: Apply DISA STIG for Red Hat Enterprise Linux 8
      when: harden_cui | bool
      ansible.builtin.include_role:
        name: redhatofficial.rhel8_cui

    - name: Apply DISA STIG for Red Hat Enterprise Linux 8
      when: harden_hipaa | bool
      ansible.builtin.include_role:
        name: redhatofficial.rhel8_hipaa