---
- name: Run linux report
  hosts: "{{ HOSTS | default('rhel') }}"
  gather_facts: false
  become: true
  vars:
    harden_firewall: false
    harden_time: false
    harden_ssh: false
    harden_pci: false
  tasks:
    # run with --skip-tags accounts_passwords_pam_faillock_deny
    - name: Apply PCI Baseline
      when: harden_pci | bool
      ansible.builtin.include_role:
        name: redhatofficial.rhel8_pci_dss